"""add click aggregations

Revision ID: 8b25f2c12829
Revises: 007_afiliados_outbox
Create Date: 2025-09-22 01:55:54.960124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b25f2c12829'
down_revision = '007_afiliados_outbox'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_estado'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_id_conversion'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_id_embajador'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_id_partner'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_id_transaccion_externa'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_eventos_outbox_afiliados_fecha_creacion'), table_name='eventos_outbox_afiliados')
    op.drop_index(op.f('ix_eventos_outbox_afiliados_id_agregado'), table_name='eventos_outbox_afiliados')
    op.drop_index(op.f('ix_eventos_outbox_afiliados_id_evento'), table_name='eventos_outbox_afiliados')
    op.drop_index(op.f('ix_eventos_outbox_afiliados_procesado'), table_name='eventos_outbox_afiliados')
    op.drop_index(op.f('ix_eventos_outbox_afiliados_tipo_evento'), table_name='eventos_outbox_afiliados')
    op.drop_table('eventos_outbox_afiliados')
    op.drop_index(op.f('ix_embajadores_email'), table_name='embajadores')
    op.drop_index(op.f('ix_embajadores_estado'), table_name='embajadores')
    op.drop_index(op.f('ix_embajadores_id'), table_name='embajadores')
    op.drop_index(op.f('ix_embajadores_id_partner'), table_name='embajadores')
    op.drop_table('embajadores')
    op.drop_index(op.f('ix_afiliados_ciudad'), table_name='afiliados')
    op.drop_index(op.f('ix_afiliados_codigo_afiliado'), table_name='afiliados')
    op.drop_index(op.f('ix_afiliados_email'), table_name='afiliados')
    op.drop_index(op.f('ix_afiliados_estado'), table_name='afiliados')
    op.drop_index(op.f('ix_afiliados_fecha_registro'), table_name='afiliados')
    op.drop_index(op.f('ix_afiliados_fecha_ultima_actividad'), table_name='afiliados')
    op.drop_index(op.f('ix_afiliados_nombre'), table_name='afiliados')
    op.drop_index(op.f('ix_afiliados_numero_documento'), table_name='afiliados')
    op.drop_index(op.f('ix_afiliados_pais'), table_name='afiliados')
    op.drop_index(op.f('ix_afiliados_tipo_afiliado'), table_name='afiliados')
    op.drop_table('afiliados')
    op.drop_index(op.f('ix_outbox_pagos_evento_id'), table_name='outbox_pagos')
    op.drop_index(op.f('ix_outbox_pagos_evento_tipo'), table_name='outbox_pagos')
    op.drop_index(op.f('ix_outbox_pagos_timestamp'), table_name='outbox_pagos')
    op.drop_table('outbox_pagos')
    op.drop_index(op.f('ix_eventos_pago_id_pago'), table_name='eventos_pago')
    op.drop_index(op.f('ix_eventos_pago_timestamp'), table_name='eventos_pago')
    op.drop_index(op.f('ix_eventos_pago_tipo_evento'), table_name='eventos_pago')
    op.drop_table('eventos_pago')
    op.create_index(op.f('ix_atribuciones_id'), 'atribuciones', ['id'], unique=False)
    op.add_column('clicks', sa.Column('total_conversiones', sa.Integer(), nullable=True))
    op.add_column('clicks', sa.Column('valor_total', sa.Float(), nullable=True))
    op.add_column('clicks', sa.Column('comision_total', sa.Float(), nullable=True))
    op.drop_constraint(op.f('conversiones_id_click_fkey'), 'conversiones', type_='foreignkey')
    op.create_foreign_key(None, 'conversiones', 'clicks', ['id_click'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversiones', type_='foreignkey')
    op.create_foreign_key(op.f('conversiones_id_click_fkey'), 'conversiones', 'clicks', ['id_click'], ['id'], ondelete='SET NULL')
    op.drop_column('clicks', 'comision_total')
    op.drop_column('clicks', 'valor_total')
    op.drop_column('clicks', 'total_conversiones')
    op.drop_index(op.f('ix_atribuciones_id'), table_name='atribuciones')
    op.create_table('eventos_pago',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_pago', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo_evento', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('datos_evento', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('version_evento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('eventos_pago_pkey'))
    )
    op.create_index(op.f('ix_eventos_pago_tipo_evento'), 'eventos_pago', ['tipo_evento'], unique=False)
    op.create_index(op.f('ix_eventos_pago_timestamp'), 'eventos_pago', ['timestamp'], unique=False)
    op.create_index(op.f('ix_eventos_pago_id_pago'), 'eventos_pago', ['id_pago'], unique=False)
    op.create_table('outbox_pagos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('evento_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('evento_tipo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('evento_datos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('publicado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fecha_publicacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reintentos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('outbox_pagos_pkey')),
    sa.UniqueConstraint('evento_id', name=op.f('outbox_pagos_evento_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_outbox_pagos_timestamp'), 'outbox_pagos', ['timestamp'], unique=False)
    op.create_index(op.f('ix_outbox_pagos_evento_tipo'), 'outbox_pagos', ['evento_tipo'], unique=False)
    op.create_index(op.f('ix_outbox_pagos_evento_id'), 'outbox_pagos', ['evento_id'], unique=False)
    op.create_table('afiliados',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('codigo_afiliado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tipo_afiliado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ciudad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pais', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('codigo_postal', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tipo_documento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('numero_documento', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nombre_fiscal', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('direccion_fiscal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comision_porcentaje', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('limite_mensual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metodo_pago_preferido', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('notificaciones_email', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notificaciones_sms', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_ultima_actividad', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadatos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('afiliados_pkey'))
    )
    op.create_index(op.f('ix_afiliados_tipo_afiliado'), 'afiliados', ['tipo_afiliado'], unique=False)
    op.create_index(op.f('ix_afiliados_pais'), 'afiliados', ['pais'], unique=False)
    op.create_index(op.f('ix_afiliados_numero_documento'), 'afiliados', ['numero_documento'], unique=False)
    op.create_index(op.f('ix_afiliados_nombre'), 'afiliados', ['nombre'], unique=False)
    op.create_index(op.f('ix_afiliados_fecha_ultima_actividad'), 'afiliados', ['fecha_ultima_actividad'], unique=False)
    op.create_index(op.f('ix_afiliados_fecha_registro'), 'afiliados', ['fecha_registro'], unique=False)
    op.create_index(op.f('ix_afiliados_estado'), 'afiliados', ['estado'], unique=False)
    op.create_index(op.f('ix_afiliados_email'), 'afiliados', ['email'], unique=True)
    op.create_index(op.f('ix_afiliados_codigo_afiliado'), 'afiliados', ['codigo_afiliado'], unique=True)
    op.create_index(op.f('ix_afiliados_ciudad'), 'afiliados', ['ciudad'], unique=False)
    op.create_table('embajadores',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(), server_default=sa.text("'PENDIENTE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('id_partner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('total_referidos', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('comisiones_ganadas', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('embajadores_pkey'))
    )
    op.create_index(op.f('ix_embajadores_id_partner'), 'embajadores', ['id_partner'], unique=False)
    op.create_index(op.f('ix_embajadores_id'), 'embajadores', ['id'], unique=False)
    op.create_index(op.f('ix_embajadores_estado'), 'embajadores', ['estado'], unique=False)
    op.create_index(op.f('ix_embajadores_email'), 'embajadores', ['email'], unique=True)
    op.create_table('eventos_outbox_afiliados',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_evento', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tipo_evento', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id_agregado', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('datos_evento', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_procesamiento', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('procesado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('intentos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('eventos_outbox_afiliados_pkey'))
    )
    op.create_index(op.f('ix_eventos_outbox_afiliados_tipo_evento'), 'eventos_outbox_afiliados', ['tipo_evento'], unique=False)
    op.create_index(op.f('ix_eventos_outbox_afiliados_procesado'), 'eventos_outbox_afiliados', ['procesado'], unique=False)
    op.create_index(op.f('ix_eventos_outbox_afiliados_id_evento'), 'eventos_outbox_afiliados', ['id_evento'], unique=True)
    op.create_index(op.f('ix_eventos_outbox_afiliados_id_agregado'), 'eventos_outbox_afiliados', ['id_agregado'], unique=False)
    op.create_index(op.f('ix_eventos_outbox_afiliados_fecha_creacion'), 'eventos_outbox_afiliados', ['fecha_creacion'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_embajador', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id_partner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id_conversion', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('moneda', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tipo_pago', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metodo_pago', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_procesamiento', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_finalizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('motivo_fallo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_transaccion_externa', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('metadatos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pagos_pkey'))
    )
    op.create_index(op.f('ix_pagos_id_transaccion_externa'), 'pagos', ['id_transaccion_externa'], unique=False)
    op.create_index(op.f('ix_pagos_id_partner'), 'pagos', ['id_partner'], unique=False)
    op.create_index(op.f('ix_pagos_id_embajador'), 'pagos', ['id_embajador'], unique=False)
    op.create_index(op.f('ix_pagos_id_conversion'), 'pagos', ['id_conversion'], unique=False)
    op.create_index(op.f('ix_pagos_estado'), 'pagos', ['estado'], unique=False)
    # ### end Alembic commands ###